// src/components/layout/Footer.tsx
import React from "react";
import instagramIcon from "assets/images/icons/instagram-icon.svg";
import twitterIcon from "assets/images/icons/twitter-icon.svg";

interface FooterLinks {
  icon: string;
  link: string;
}

const footerLinks: readonly FooterLinks[] = [
  { icon: instagramIcon, link: "https://www.instagram.com" },
  { icon: twitterIcon, link: "https://www.twitter.com" },
];

const Footer: React.FC = () => {
  return (
    <div className="py-5 flex items-center bg-[#012E40] justify-center">
      <ul className="flex justify-center space-x-4">
        {footerLinks.map((footerLink, index) => (
          <li key={index}>
            <a href={footerLink.link} target="_blank" rel="noopener noreferrer">
              <img
                src={footerLink.icon}
                alt="icon"
                height="35px"
                width="35px"
              />
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Footer;

// src/components/common/Footer.svelte
<script lang="ts">
	import '@/app.css';
	import instagramIcon from '@/assets/images/icons/instagram-icon.svg';
	import twitterIcon from '@/assets/images/icons/twitter-icon.svg';

	interface FooterLinks {
		icon: string;
		link: string;
	}

	let footerLinks: readonly FooterLinks[] = [
		{ icon: instagramIcon, link: 'https://www.instagram.com' },
		{ icon: twitterIcon, link: 'https://www.twitter.com' }
	];
</script>

<div class="h-[150px] flex items-center bg-[#012E40] justify-center">
	<ul class="flex justify-center space-x-4">
		{#each footerLinks as footerLink}
			<li>
				<a href={footerLink.link} target="_blank" rel="noopener noreferrer">
					<img src={footerLink.icon} alt="icon" height="35px" width="35px" />
				</a>
			</li>
		{/each}
	</ul>
</div>
